# Goal ---> To RUn the END tO END devsecops pipline 

name: devsecops

on: 
    push:
        branches: [master] 


jobs:
    # code-> security
    code-quality:
        uses: ./.github/workflows/code-quality.yml
        secrets: inherit

   # dependency-scan:
       # uses: ./github/workflows/dependency.ynl
        #secrets: inherit



           
    #biild:


    #test:


    #deploy:
