# Goal ---> To RUn the END tO END devsecops pipline 

name: devsecops

on: 
    push:
        branches: [master] 


jobs:
    # code-> security

    # code quality
    code-quality:
        uses: ./.github/workflows/code-quality.yml
        secrets: inherit

        # secret-check
    secrets-scan:
        uses: ./.github/workflows/secrets.yml
        secrets: inherit
            # dependdency check
    dependency-scan:
        uses: ./.github/workflows/dependency.yml
        secrets: inherit
        
        # dockerchcek
    Docker-scan:
        uses: ./.github/workflows/docker-scan.yml
        secrets: inherit
        
        #Sonnar qube

    sonar-scan:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit


    code-test:
        uses: ./.github/workflows/code-test.yml
        secrets: inherit
        
        
    dockerhub-push:
        needs: [ code-quality,secrets-scan,dependency-scan, Docker-scan,sonar-scan,code-test]
        uses: ./.github/workflows/docker-hub-build-push.yml
        secrets: inherit

        # Deploy the code

    deploy:
        needs: [ code-quality,secrets-scan,dependency-scan, Docker-scan,sonar-scan,code-test,dockerhub-push ]
        uses: ./.github/workflows/Cd.yml
        secrets: inherit
        
            

    
            

  #  docker-build-push:
   #     uses: ./.github/workflows/docker-build-push.yml
    #    secrets: inherit


    #test:


    #deploy:
