# Goal iHave to check the and scan the code is there and password or env get not leak 

name: secrets Scaning

on: 
    workflow_call: 


jobs:
    scan-secrets:
        runs-on: ubuntu-latest

        steps:
            - name: code checkout
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            
            - name: git leak scanneer
              id: gitleak
              uses: ariuszPorowski/github-action-gitleaks@v2
              with:
                fail: false