# Goal ---> i have to scan my code have code coverage doesn't have any security issue/thread
name: sonar-scan

on: 
    workflow_call: 

jobs:
    sonar-scan:
        runs-on: ubuntu-latest
        
        steps:
            - name: code checkout
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: sonarqube scan
              uses:  SonarSource/sonarqube-scan-action@v8
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

             